// appendices.js
// Common appendix sentences for the Lesions field.
window.appendicesCandidates = [
"Extraosseous radioactivity over left hand may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right hand may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left upper arm may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right upper arm may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left elbow may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right elbow may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left forearm may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right forearm may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left wrist may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right wrist may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left knee may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right knee may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left lower leg may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right lower leg may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left ankle may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right ankle may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left foot may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over right foot may indicate presence of radiotracer extravasation.",
"Extraosseous radioactivity over left hand may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right hand may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left upper arm may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right upper arm may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left elbow may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right elbow may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left forearm may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right forearm may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left wrist may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right wrist may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left knee may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right knee may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left lower leg may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right lower leg may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left ankle may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right ankle may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left foot may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over right foot may indicate presence of radiotracer extravasation and/or radiotracer accumulation in catheter.",
"Extraosseous radioactivity over left renal area may indicate hydronephrosis.",
"Extraosseous radioactivity over right renal area may indicate hydronephrosis.",
"Extraosseous radioactivity over bilateral renal areas may indicate hydronephrosis.",
"Extraosseous radioactivity over pelvic area may indicate radiotracer accumulation in ileal conduit.",
"No visualization of left kidney may indicate s/p nephrectomy.",
"No visualization of right kidney may indicate s/p nephrectomy.",
"No visualization of bilateral kidneys may indicate s/p nephrectomy.",
"Faint visualization of left kidney may indicate poor renal function.",
"Faint visualization of right kidney may indicate poor renal function.",
"Faint visualization of bilateral kidneys may indicate poor renal function.",
"Faint visualization of bilateral kidneys may indicate superscan.",
"Increased radioactivity in epiphyseal plates of long bones of four limbs may indicate presence of growth plates.",
"Lateral deviation of T-L spine may indicate scoliosis.",
"Lateral deviation of T spine may indicate scoliosis.",
"Lateral deviation of L spine may indicate scoliosis.",
"Cold area of left hip may indicate status post arthroplasty.",
"Cold area of right hip may indicate status post arthroplasty.",
"Cold area of bilateral hips may indicate status post arthroplasty.",
"Cold area of left knee may indicate status post arthroplasty.",
"Cold area of right knee may indicate status post arthroplasty.",
"Cold area of bilateral knees may indicate status post arthroplasty.",
"Cold area of left hip and left knee may indicate status post arthroplasty.",
"Cold area of right hip and right knee may indicate status post arthroplasty.",
"Cold area of right hip and left knee may indicate status post arthroplasty.",
"Cold area of left hip and right knee may indicate status post arthroplasty.",
"Cold area of bilateral hips and left knee may indicate status post arthroplasty.",
"Cold area of bilateral hips and right knee may indicate status post arthroplasty.",
"Cold area of left hip and bilateral knees may indicate status post arthroplasty.",
"Cold area of right hip and bilateral knees may indicate status post arthroplasty.",
"Cold area of bilateral hips and bilateral knees may indicate status post arthroplasty.",
"Increased radioactivity over may indicate contamination.",
"Extraosseous radioactivity in right pelvic area may indicate transplant kidney.",
"Extraosseous radioactivity in left pelvic area may indicate transplant kidney.",
"Bilateral linear stripes of increased activity along cortex of long bones of extremities may indicate hypertrophic pulmonary osteoarthropathy.",
"Hot spot over right elbow may indicate presence of radiotracer injection site.",
"Hot spot over right hand may indicate presence of radiotracer injection site.",
"Extraosseous radioactivity over left upper abdominal wall and right forearm may indicate presence of radiotracer extravasation.",
"Faint extraosseous radioactivity over right upper abdomen may indicate hepatic tumor/ascites.",
"Radiotracer accumulation in dilated left renal pelvis may indicate hydronephrosis.",
"Radiotracer accumulation in dilated left renal pelvis and left ureter may indicate hydronephrosis.",
"Poor visualization of left kidney may indicate very poor left renal function.",
"Poor visualization of right kidney may indicate very poor right renal function.",
"Poor visualization of bilateral kidneys may indicate very poor bilateral renal function.",
"No visualization of left kidney may indicate poor renal function.",
"No visualization of right kidney may indicate poor renal function.",
"No visualization of bilateral kidneys may indicate poor renal function.",
"Cold area in right 3rd-5th rib may indicate previous operation."
];
