// impressions.js
// 請在此修改 Impressions 欄位的候選項內容
window.impressionsCandidates = [
  "Compatible with bone metastasis in {}.",
  "Compatible with bone metastasis in {}. But flare phenomenon secondary to recent therapy cannot be excluded.",
  "Compatible with bone metastasis in {}. But flare phenomenon secondary to recent therapy cannot be excluded completely.",
  "Compatible with pathological fracture in {}.",
  "Compatible with LCH involvement in {}.",
  "Compatible with tumor involvement in {}.",
  "Suspect bone metastasis in {}.",
  "Suspect bone metastasis in {}. But flare phenomenon secondary to recent therapy cannot be excluded.",
  "Suspect bone metastasis in {}. But flare phenomenon secondary to recent therapy cannot be excluded completely.",
  "Suspect pathological fracture in {}.",
  "Suspect LCH involvement in {}.",
  "Suspect tumor involvement in {}.",
  "Possible bone metastasis in {}.",
  "Possible bone metastasis in {}. But flare phenomenon secondary to recent therapy cannot be excluded.",
  "Possible bone metastasis in {}. But flare phenomenon secondary to recent therapy cannot be excluded completely.",
  "Possible pathological fracture in {}.",
  "Possible LCH involvement in {}.",
  "Possible tumor involvement in {}.",

  "Bone lesion in {}, possibly bone metastasis or tumor involvement.",
  "Bone lesion in {}, possibly bone metastasis or reactive change.",
  "Bone lesion in {}, possibly bone metastasis or post-treatment change.",
  "Bone lesion in {}, possibly bone metastasis or post-radiotherapy change.",
  "Bone lesion in {}, possibly bone metastasis or post-operative change.",
  "Bone lesion in {}, possibly bone metastasis or traumatic insult.",
  "Bone lesion in {}, possibly bone metastasis or arthritis.",
  "Bone lesion in {}, bone metastasis cannot be excluded.",
  "Bone lesion in {}, pathological fracture cannot be excluded.",
  "Bone lesion in {}, LCH involvement cannot be excluded.",
  "Bone lesion in {}, tumor involvement cannot be excluded.",
  "Bone lesion in {}, reactive change cannot be excluded.",
  "Bone lesion in {}, possibly tumor involvement or reactive change.",
  "Bone lesion in {}, possibly tumor involvement or post-treatment change.",
  "Bone lesion in {}, possibly tumor involvement or post-radiotherapy change.",
  "Bone lesion in {}, possibly tumor involvement or post-operative change.",
  "Bone lesion in {}, possibly tumor involvement or traumatic insult.",
  "Bone lesion in {}, possibly tumor involvement or arthritis.",
  "Bone lesion in {}, possibly reactive change or post-treatment change.",
  "Bone lesion in {}, possibly reactive change or post-radiotherapy change.",
  "Bone lesion in {}, possibly reactive change or post-operative change.",
  "Bone lesion in {}, possibly reactive change or traumatic insult.",
  "Bone lesion in {}, bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, pathological fracture cannot be completely excluded.",
  "Bone lesion in {}, LCH involvement cannot be completely excluded.",
  "Bone lesion in {}, tumor involvement cannot be completely excluded.",
  "Bone lesion in {}, reactive change cannot be completely excluded.",
  "Bone lesion in {}, bone metastasis should be considered if without traumatic history.",
  "Bone lesion in {}, possibly reactive change, but bone metastasis cannot be excluded.",
  "Bone lesion in {}, possibly reactive change, but bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, possibly post-treatment change, but bone metastasis cannot be excluded.",
  "Bone lesion in {}, possibly post-treatment change, but bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, possibly post-radiotherapy change, but bone metastasis cannot be excluded.",
  "Bone lesion in {}, possibly post-radiotherapy change, but bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, possibly post-operative change, but bone metastasis cannot be excluded.",
  "Bone lesion in {}, possibly post-operative change, but bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, possibly traumatic insult, but bone metastasis cannot be excluded.",
  "Bone lesion in {}, possibly traumatic insult, but bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, possibly arthritis, but bone metastasis cannot be excluded.",
  "Bone lesion in {}, possibly arthritis, but bone metastasis cannot be completely excluded.",
  "Bone lesion in {}, possibly osteoporotic compression fracture, but pathological fracture cannot be excluded.",
  "Bone lesion in {}, possibly osteoporotic compression fracture, but pathological fracture cannot be completely excluded.",

  "Bone lesion in {}, further evaluation and/or follow-up bone scan is recommended.",
  "Bone lesion in {}, further evaluation and/or follow-up bone scan is recommended to exclude bone metastasis.",
  "Bone lesion in {}, further evaluation and/or follow-up bone scan is recommended to exclude bone malignancy.",
  "Bone lesion in {}, further evaluation is recommended.",
  "Bone lesion in {}, further evaluation is recommended to exclude bone metastasis.",
  "Bone lesion in {}, further evaluation is recommended to exclude bone malignancy.",
  "Bone lesion in {}, traumatic history review and/or follow-up bone scan is recommended.",
  "Bone lesion in {}, traumatic history review and/or follow-up bone scan is recommended to exclude bone metastasis.",
  "Bone lesion in {}, traumatic history review and/or follow-up bone scan is recommended to exclude bone malignancy.",
  "Bone lesion in {}, traumatic history review is recommended.",
  "Bone lesion in {}, traumatic history review is recommended to exclude bone metastasis.",
  "Bone lesion in {}, traumatic history review is recommended to exclude bone malignancy.",
  "Bone lesion in {}, follow-up bone scan is recommended.",
  "Bone lesion in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Bone lesion in {}, follow-up bone scan is recommended to exclude bone malignancy.",
  "Bone lesion in {}, imaging correlation is recommended.",
  "Bone lesion in {}, imaging correlation is recommended to exclude bone metastasis.",
  "Bone lesion in {}, imaging correlation is recommended to exclude bone malignancy.",
  "Bone lesion in {}, follow-up bone scan and/or imaging correlation is recommended.",
  "Bone lesion in {}, follow-up bone scan and/or imaging correlation is recommended to exclude bone metastasis.",
  "Bone lesion in {}, follow-up bone scan and/or imaging correlation is recommended to exclude bone malignancy.",
  "Possible reactive change in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Possible post-treatment change in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Possible post-radiotherapy change in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Possible post-operative change in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Possible traumatic insult in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Possible arthritis in {}, follow-up bone scan is recommended to exclude bone metastasis.",
  "Possible osteoporotic compression fracture in {}, follow-up bone scan is recommended to exclude pathological fracture.",
  "Suspicious bone lesion in {}, follow-up bone scan is recommended to exclude bone metastasis.",

  "Suspect recent compression fracture in {}, follow-up bone scan is recommended.",
  "Suspect compression fracture in {}, follow-up bone scan is recommended.",
  "Suspect reactive change in {}, follow-up bone scan is recommended.",
  "Suspect post-treatment change in {}, follow-up bone scan is recommended.",
  "Suspect post-radiotherapy change in {}, follow-up bone scan is recommended.",
  "Suspect post-operative change in {}, follow-up bone scan is recommended.",
  "Suspect traumatic insult in {}, follow-up bone scan is recommended.",
  "Suspect arthritis in {}, follow-up bone scan is recommended.",
  "Suspect insufficiency fracture in {}, follow-up bone scan is recommended.",
  "Suspect previous compression fracture in {}, follow-up bone scan is recommended.",
  "Suspect previous insult in {}, follow-up bone scan is recommended.",
  "Possible recent compression fracture in {}, follow-up bone scan is recommended.",
  "Possible compression fracture in {}, follow-up bone scan is recommended.",
  "Possible compression fracture or arthritis in {}, follow-up bone scan is recommended.",
  "Possible reactive change in {}, follow-up bone scan is recommended.",
  "Possible post-treatment change in {}, follow-up bone scan is recommended.",
  "Possible post-radiotherapy change in {}, follow-up bone scan is recommended.",
  "Possible post-operative change in {}, follow-up bone scan is recommended.",
  "Possible traumatic insult or arthritis in {}, follow-up bone scan is recommended.",
  "Possible traumatic insult in {}, follow-up bone scan is recommended.",
  "Possible arthritis in {}, follow-up bone scan is recommended.",
  "Possible post-operative change or arthritis in {}, follow-up bone scan is recommended.",
  "Possible insufficiency fracture in {}, follow-up bone scan is recommended.",
  "Possible previous compression fracture in {}, follow-up bone scan is recommended.",
  "Possible previous insult in {}, follow-up bone scan is recommended.",
  "Suspect recent compression fracture in {}.",
  "Suspect compression fracture in {}.",
  "Suspect reactive change in {}.",
  "Suspect post-treatment change in {}.",
  "Suspect post-radiotherapy change in {}.",
  "Suspect post-operative change in {}.",
  "Suspect traumatic insult in {}.",
  "Suspect arthritis in {}.",
  "Suspect insufficiency fracture in {}.",
  "Suspect previous compression fracture in {}.",
  "Suspect previous insult in {}.",
  "Possible recent compression fracture in {}.",
  "Possible compression fracture in {}.",
  "Possible compression fracture or arthritis in {}.",
  "Possible reactive change in {}.",
  "Possible post-treatment change in {}.",
  "Possible post-radiotherapy change in {}.",
  "Possible post-operative change in {}.",
  "Possible traumatic insult or arthritis in {}.",
  "Possible traumatic insult in {}.",
  "Possible arthritis in {}.",
  "Possible post-operative change or arthritis in {}.",
  "Possible insufficiency fracture in {}.",
  "Possible previous compression fracture in {}.",
  "Possible previous insult in {}.",
  "Bone lesion in {}, possibly benign in nature.",
  "Suspect compression fracture s/p and with post-operative change in {}.",
  "Suspect arthritis s/p and with post-operative change in {}.",
  "Suspect traumatic insult s/p and with post-operative change in {}.",
  "Suspect osteonecrosis in {}.",
  "Possible osteonecrosis in {}.",
  "Possible dental problem or osteonecrosis in {}.",
  "Bone lesion in {}, osteonecrosis cannot be excluded.",
  "Bone lesion in {}, possibly traumatic insult, arthritis, or osteonecrosis.",
  "Bone lesion in {}, imaging correlation is recommended to exclude osteonecrosis.",
  "Possible dental problem in {}, follow-up bone scan is recommended.",
  "Suspect dental problem in {}, follow-up bone scan is recommended.",
  "Suspect dental problem in {}.",
  "Possible non-specific finding in {}, follow-up bone scan is recommended.",
  "Suspect non-specific finding in {}, follow-up bone scan is recommended.",
  "Suspect non-specific finding in {}.",
  "Possible normal variant in {}, follow-up bone scan is recommended.",
  "Suspect normal variant in {}.",
  "Possible derangement in {}.",
  "Possible sinusitis in {}.",
  "Possible mastoiditis in {}.",
  "Possible tendinitis in {}.",
  "Possible enthesopathy in {}.",
  "Possible hypertrophic pulmonary osteoarthropathy in {}, follow-up bone scan is recommended.",
  "Suspect derangement in {}.",
  "Suspect sinusitis in {}.",
  "Suspect mastoiditis in {}.",
  "Suspect tendinitis in {}.",
  "Suspect enthesopathy in {}.",
  "Suspect hypertrophic pulmonary osteoarthropathy in {}.",
  "Faint bone lesion in {}, follow-up bone scan is recommended.",
  "Faint bone lesion in {}, possibly non-specific finding.",
  "Faint bone lesion in {}, possibly previous insult.",
  "Doubtful bone lesion in {}, follow-up bone scan is recommended.",
  "Doubtful bone lesion in {}, possibly non-specific finding.",
  "Doubtful bone lesion in {}, possibly previous insult.",
];
