// lesions.js
// 請在此修改 Lesions 欄位的候選項內容
window.lesionsCandidates = [
"skull",
"skull base",
"left skull base",
"right skull base",
"ethmoid bone",
"bilateral frontal bone",
"frontal bone",
"bilateral supraorbital areas of frontal bone",
"left supraorbital area of frontal bone",
"right supraorbital area of frontal bone",
"left frontal bone",
"right frontal bone",
"bilateral frontal/parietal bones",
"left frontal/parietal bone",
"right frontal/parietal bone",
"bilateral parietal bones",
"parietal bones",
"left parietal bone",
"right parietal bone",
"bilateral temporal bones",
"left temporal bone",
"right temporal bone",
"bilateral temporal mastoid processes",
"left temporal mastoid process",
"right temporal mastoid process",
"bilateral occipital bone",
"occipital bone",
"left occipital bone",
"right occipital bone",
"bilateral zygomatic bone",
"left zygomatic bone",
"right zygomatic bone",
"bilateral maxilla",
"maxilla",
"left maxilla",
"right maxilla",
"bilateral mandible",
"mandible",
"left mandible",
"right mandible",
"bilateral temporomandibular joints",
"left temporomandibular joint",
"right temporomandibular joint",
"bilateral paranasal areas",
"paranasal area",
"left paranasal area",
"right paranasal area",
"C-T-L-S spine",
"C-T-L spine",
"C-T spine",
"C-spine",
"upper C-spine",
"middle C-spine",
"lower C-spine",
"C1",
"C1-C2",
"C2",
"C2-C3",
"C3",
"C3-C4",
"C4",
"C4-C5",
"C5",
"C5-C6",
"C6",
"C6-C7",
"C7",
"C7-T1",
"vertebral body of C1",
"vertebral body of C2",
"vertebral body of C3",
"vertebral body of C4",
"vertebral body of C5",
"vertebral body of C6",
"vertebral body of C7",
"endplates of C1-C2",
"endplates of C2-C3",
"endplates of C3-C4",
"endplates of C4-C5",
"endplates of C5-C6",
"endplates of C6-C7",
"endplates of C7-T1",
"bilateral facet joints of C1-C2",
"left facet joint of C1-C2",
"right facet joint of C1-C2",
"bilateral facet joints of C2-C3",
"left facet joint of C2-C3",
"right facet joint of C2-C3",
"bilateral facet joints of C3-C4",
"left facet joint of C3-C4",
"right facet joint of C3-C4",
"bilateral facet joints of C4-C5",
"left facet joint of C4-C5",
"right facet joint of C4-C5",
"bilateral facet joints of C5-C6",
"left facet joint of C5-C6",
"right facet joint of C5-C6",
"bilateral facet joints of C6-C7",
"left facet joint of C6-C7",
"right facet joint of C6-C7",
"bilateral facet joints of C7-T1",
"left facet joint of C7-T1",
"right facet joint of C7-T1",
"T-L-S spine",
"T-L spine",
"T-spine",
"upper T-spine",
"middle T-spine",
"T1",
"T1-T2",
"T2",
"T2-T3",
"T3",
"T3-T4",
"T4",
"T4-T5",
"T5",
"T5-T6",
"T6",
"T6-T7",
"T7",
"T7-T8",
"T8",
"T8-T9",
"T9",
"T9-T10",
"T10",
"T10-T11",
"T11",
"T11-T12",
"T12",
"T12-L1",
"vertebral body of T1",
"vertebral body of T2",
"vertebral body of T3",
"vertebral body of T4",
"vertebral body of T5",
"vertebral body of T6",
"vertebral body of T7",
"vertebral body of T8",
"vertebral body of T9",
"vertebral body of T10",
"vertebral body of T11",
"vertebral body of T12",
"endplates of T1-T2",
"endplates of T2-T3",
"endplates of T3-T4",
"endplates of T4-T5",
"endplates of T5-T6",
"endplates of T6-T7",
"endplates of T7-T8",
"endplates of T8-T9",
"endplates of T9-T10",
"endplates of T10-T11",
"endplates of T11-T12",
"endplates of T12-L1",
"bilateral facet joints of T1-T2",
"left facet joint of T1-T2",
"right facet joint of T1-T2",
"bilateral facet joints of T2-T3",
"left facet joint of T2-T3",
"right facet joint of T2-T3",
"bilateral facet joints of T3-T4",
"left facet joint of T3-T4",
"right facet joint of T3-T4",
"bilateral facet joints of T4-T5",
"left facet joint of T4-T5",
"right facet joint of T4-T5",
"bilateral facet joints of T5-T6",
"left facet joint of T5-T6",
"right facet joint of T5-T6",
"bilateral facet joints of T6-T7",
"left facet joint of T6-T7",
"right facet joint of T6-T7",
"bilateral facet joints of T7-T8",
"left facet joint of T7-T8",
"right facet joint of T7-T8",
"bilateral facet joints of T8-T9",
"left facet joint of T8-T9",
"right facet joint of T8-T9",
"bilateral facet joints of T9-T10",
"left facet joint of T9-T10",
"right facet joint of T9-T10",
"bilateral facet joints of T10-T11",
"left facet joint of T10-T11",
"right facet joint of T10-T11",
"bilateral facet joints of T11-T12",
"left facet joint of T11-T12",
"right facet joint of T11-T12",
"bilateral facet joints of T12-L1",
"left facet joint of T12-L1",
"right facet joint of T12-L1",
"L-S spine",
"L-spine",
"lower L-spine",
"L1",
"L1-L2",
"L2",
"L2-L3",
"L3",
"L3-L4",
"L4",
"L4-L5",
"L5",
"L5-S1",
"S1",
"vertebral body of L1",
"vertebral body of L2",
"vertebral body of L3",
"vertebral body of L4",
"vertebral body of L5",
"endplates of L1-L2",
"endplates of L2-L3",
"endplates of L3-L4",
"endplates of L4-L5",
"endplates of L5-S1",
"bilateral facet joints of L1-L2",
"left facet joint of L1-L2",
"right facet joint of L1-L2",
"bilateral facet joints of L2-L3",
"left facet joint of L2-L3",
"right facet joint of L2-L3",
"bilateral facet joints of L3-L4",
"left facet joint of L3-L4",
"right facet joint of L3-L4",
"bilateral facet joints of L4-L5",
"left facet joint of L4-L5",
"right facet joint of L4-L5",
"bilateral facet joints of L5-S1",
"left facet joint of L5-S1",
"right facet joint of L5-S1",
"sacrum and coccyx",
"sacrum",
"bilateral sacrum",
"upper sacrum",
"midline sacrum",
"lower sacrum",
"left sacrum",
"right sacrum",
"coccyx",
"bilateral SI joints",
"left SI joint",
"right SI joint",
"thorax",
"sternum",
"sternal body",
"sternal angle",
"sternal manubrium",
"left sternum",
"right sternum",
"bilateral sternoclavicular joints",
"left sternoclavicular joint",
"right sternoclavicular joint",
"ribs",
"bilateral ribs",
"left ribs",
"right ribs",
"bilateral 1st ribs",
"anterior aspect of bilateral 1st ribs",
"anterior aspect of left 1st rib",
"anterior aspect of right 1st rib",
"anterolateral aspect of bilateral 1st ribs",
"anterolateral aspect of left 1st rib",
"anterolateral aspect of right 1st rib",
"lateral aspect of bilateral 1st ribs",
"lateral aspect of left 1st rib",
"lateral aspect of right 1st rib",
"posterior aspect of bilateral 1st ribs",
"posterior aspect of left 1st rib",
"posterior aspect of right 1st rib",
"posterolateral aspect of bilateral 1st ribs",
"posterolateral aspect of left 1st rib",
"posterolateral aspect of right 1st rib",
"left 1st rib",
"right 1st rib",
"bilateral 2nd ribs",
"anterior aspect of bilateral 2nd ribs",
"anterior aspect of left 2nd rib",
"anterior aspect of right 2nd rib",
"anterolateral aspect of bilateral 2nd ribs",
"anterolateral aspect of left 2nd rib",
"anterolateral aspect of right 2nd rib",
"lateral aspect of bilateral 2nd ribs",
"lateral aspect of left 2nd rib",
"lateral aspect of right 2nd rib",
"posterior aspect of bilateral 2nd ribs",
"posterior aspect of left 2nd rib",
"posterior aspect of right 2nd rib",
"posterolateral aspect of bilateral 2nd ribs",
"posterolateral aspect of left 2nd rib",
"posterolateral aspect of right 2nd rib",
"left 2nd rib",
"right 2nd rib",
"bilateral 3rd ribs",
"anterior aspect of bilateral 3rd ribs",
"anterior aspect of left 3rd rib",
"anterior aspect of right 3rd rib",
"anterolateral aspect of bilateral 3rd ribs",
"anterolateral aspect of left 3rd rib",
"anterolateral aspect of right 3rd rib",
"lateral aspect of bilateral 3rd ribs",
"lateral aspect of left 3rd rib",
"lateral aspect of right 3rd rib",
"posterior aspect of bilateral 3rd ribs",
"posterior aspect of left 3rd rib",
"posterior aspect of right 3rd rib",
"posterolateral aspect of bilateral 3rd ribs",
"posterolateral aspect of left 3rd rib",
"posterolateral aspect of right 3rd rib",
"left 3rd rib",
"right 3rd rib",
"bilateral 4th ribs",
"anterior aspect of bilateral 4th ribs",
"anterior aspect of left 4th rib",
"anterior aspect of right 4th rib",
"anterolateral aspect of bilateral 4th ribs",
"anterolateral aspect of left 4th rib",
"anterolateral aspect of right 4th rib",
"lateral aspect of bilateral 4th ribs",
"lateral aspect of left 4th rib",
"lateral aspect of right 4th rib",
"posterior aspect of bilateral 4th ribs",
"posterior aspect of left 4th rib",
"posterior aspect of right 4th rib",
"posterolateral aspect of bilateral 4th ribs",
"posterolateral aspect of left 4th rib",
"posterolateral aspect of right 4th rib",
"left 4th rib",
"right 4th rib",
"bilateral 5th ribs",
"anterior aspect of bilateral 5th ribs",
"anterior aspect of left 5th rib",
"anterior aspect of right 5th rib",
"anterolateral aspect of bilateral 5th ribs",
"anterolateral aspect of left 5th rib",
"anterolateral aspect of right 5th rib",
"lateral aspect of bilateral 5th ribs",
"lateral aspect of left 5th rib",
"lateral aspect of right 5th rib",
"posterior aspect of bilateral 5th ribs",
"posterior aspect of left 5th rib",
"posterior aspect of right 5th rib",
"posterolateral aspect of bilateral 5th ribs",
"posterolateral aspect of left 5th rib",
"posterolateral aspect of right 5th rib",
"left 5th rib",
"right 5th rib",
"bilateral 6th ribs",
"anterior aspect of bilateral 6th ribs",
"anterior aspect of left 6th rib",
"anterior aspect of right 6th rib",
"anterolateral aspect of bilateral 6th ribs",
"anterolateral aspect of left 6th rib",
"anterolateral aspect of right 6th rib",
"lateral aspect of bilateral 6th ribs",
"lateral aspect of left 6th rib",
"lateral aspect of right 6th rib",
"posterior aspect of bilateral 6th ribs",
"posterior aspect of left 6th rib",
"posterior aspect of right 6th rib",
"posterolateral aspect of bilateral 6th ribs",
"posterolateral aspect of left 6th rib",
"posterolateral aspect of right 6th rib",
"left 6th rib",
"right 6th rib",
"bilateral 7th ribs",
"anterior aspect of bilateral 7th ribs",
"anterior aspect of left 7th rib",
"anterior aspect of right 7th rib",
"anterolateral aspect of bilateral 7th ribs",
"anterolateral aspect of left 7th rib",
"anterolateral aspect of right 7th rib",
"lateral aspect of bilateral 7th ribs",
"lateral aspect of left 7th rib",
"lateral aspect of right 7th rib",
"posterior aspect of bilateral 7th ribs",
"posterior aspect of left 7th rib",
"posterior aspect of right 7th rib",
"posterolateral aspect of bilateral 7th ribs",
"posterolateral aspect of left 7th rib",
"posterolateral aspect of right 7th rib",
"left 7th rib",
"right 7th rib",
"bilateral 8th ribs",
"anterior aspect of bilateral 8th ribs",
"anterior aspect of left 8th rib",
"anterior aspect of right 8th rib",
"anterolateral aspect of bilateral 8th ribs",
"anterolateral aspect of left 8th rib",
"anterolateral aspect of right 8th rib",
"lateral aspect of bilateral 8th ribs",
"lateral aspect of left 8th rib",
"lateral aspect of right 8th rib",
"posterior aspect of bilateral 8th ribs",
"posterior aspect of left 8th rib",
"posterior aspect of right 8th rib",
"posterolateral aspect of bilateral 8th ribs",
"posterolateral aspect of left 8th rib",
"posterolateral aspect of right 8th rib",
"left 8th rib",
"right 8th rib",
"bilateral 9th ribs",
"anterior aspect of bilateral 9th ribs",
"anterior aspect of left 9th rib",
"anterior aspect of right 9th rib",
"anterolateral aspect of bilateral 9th ribs",
"anterolateral aspect of left 9th rib",
"anterolateral aspect of right 9th rib",
"lateral aspect of bilateral 9th ribs",
"lateral aspect of left 9th rib",
"lateral aspect of right 9th rib",
"posterior aspect of bilateral 9th ribs",
"posterior aspect of left 9th rib",
"posterior aspect of right 9th rib",
"posterolateral aspect of bilateral 9th ribs",
"posterolateral aspect of left 9th rib",
"posterolateral aspect of right 9th rib",
"left 9th rib",
"right 9th rib",
"bilateral 10th ribs",
"anterior aspect of bilateral 10th ribs",
"anterior aspect of left 10th rib",
"anterior aspect of right 10th rib",
"anterolateral aspect of bilateral 10th ribs",
"anterolateral aspect of left 10th rib",
"anterolateral aspect of right 10th rib",
"lateral aspect of bilateral 10th ribs",
"lateral aspect of left 10th rib",
"lateral aspect of right 10th rib",
"posterior aspect of bilateral 10th ribs",
"posterior aspect of left 10th rib",
"posterior aspect of right 10th rib",
"posterolateral aspect of bilateral 10th ribs",
"posterolateral aspect of left 10th rib",
"posterolateral aspect of right 10th rib",
"left 10th rib",
"right 10th rib",
"bilateral 11th ribs",
"anterior aspect of bilateral 11th ribs",
"anterior aspect of left 11th rib",
"anterior aspect of right 11th rib",
"anterolateral aspect of bilateral 11th ribs",
"anterolateral aspect of left 11th rib",
"anterolateral aspect of right 11th rib",
"lateral aspect of bilateral 11th ribs",
"lateral aspect of left 11th rib",
"lateral aspect of right 11th rib",
"posterior aspect of bilateral 11th ribs",
"posterior aspect of left 11th rib",
"posterior aspect of right 11th rib",
"posterolateral aspect of bilateral 11th ribs",
"posterolateral aspect of left 11th rib",
"posterolateral aspect of right 11th rib",
"left 11th rib",
"right 11th rib",
"bilateral 12th ribs",
"anterior aspect of bilateral 12th ribs",
"anterior aspect of left 12th rib",
"anterior aspect of right 12th rib",
"anterolateral aspect of bilateral 12th ribs",
"anterolateral aspect of left 12th rib",
"anterolateral aspect of right 12th rib",
"lateral aspect of bilateral 12th ribs",
"lateral aspect of left 12th rib",
"lateral aspect of right 12th rib",
"posterior aspect of bilateral 12th ribs",
"posterior aspect of left 12th rib",
"posterior aspect of right 12th rib",
"posterolateral aspect of bilateral 12th ribs",
"posterolateral aspect of left 12th rib",
"posterolateral aspect of right 12th rib",
"left 12th rib",
"right 12th rib",
"bilateral 1st costochondral junctions",
"left 1st costochondral junction",
"right 1st costochondral junction",
"bilateral 2nd costochondral junctions",
"left 2nd costochondral junction",
"right 2nd costochondral junction",
"bilateral 3rd costochondral junctions",
"left 3rd costochondral junction",
"right 3rd costochondral junction",
"bilateral 4th costochondral junctions",
"left 4th costochondral junction",
"right 4th costochondral junction",
"bilateral 5th costochondral junctions",
"left 5th costochondral junction",
"right 5th costochondral junction",
"bilateral 6th costochondral junctions",
"left 6th costochondral junction",
"right 6th costochondral junction",
"bilateral 7th costochondral junctions",
"left 7th costochondral junction",
"right 7th costochondral junction",
"bilateral 8th costochondral junctions",
"left 8th costochondral junction",
"right 8th costochondral junction",
"bilateral 9th costochondral junctions",
"left 9th costochondral junction",
"right 9th costochondral junction",
"bilateral 10th costochondral junctions",
"left 10th costochondral junction",
"right 10th costochondral junction",
"bilateral 11th costochondral junctions",
"left 11th costochondral junction",
"right 11th costochondral junction",
"bilateral 12th costochondral junctions",
"left 12th costochondral junction",
"right 12th costochondral junction",
"bilateral 1st costovertebral joints",
"left 1st costovertebral joint",
"right 1st costovertebral joint",
"bilateral 2nd costovertebral joints",
"left 2nd costovertebral joint",
"right 2nd costovertebral joint",
"bilateral 3rd costovertebral joints",
"left 3rd costovertebral joint",
"right 3rd costovertebral joint",
"bilateral 4th costovertebral joints",
"left 4th costovertebral joint",
"right 4th costovertebral joint",
"bilateral 5th costovertebral joints",
"left 5th costovertebral joint",
"right 5th costovertebral joint",
"bilateral 6th costovertebral joints",
"left 6th costovertebral joint",
"right 6th costovertebral joint",
"bilateral 7th costovertebral joints",
"left 7th costovertebral joint",
"right 7th costovertebral joint",
"bilateral 8th costovertebral joints",
"left 8th costovertebral joint",
"right 8th costovertebral joint",
"bilateral 9th costovertebral joints",
"left 9th costovertebral joint",
"right 9th costovertebral joint",
"bilateral 10th costovertebral joints",
"left 10th costovertebral joint",
"right 10th costovertebral joint",
"bilateral 11th costovertebral joints",
"left 11th costovertebral joint",
"right 11th costovertebral joint",
"bilateral 12th costovertebral joints",
"left 12th costovertebral joint",
"right 12th costovertebral joint",
"bilateral 1st costosternal joints",
"left 1st costosternal joint",
"right 1st costosternal joint",
"bilateral 2nd costosternal joints",
"left 2nd costosternal joint",
"right 2nd costosternal joint",
"bilateral 3rd costosternal joints",
"left 3rd costosternal joint",
"right 3rd costosternal joint",
"bilateral 4th costosternal joints",
"left 4th costosternal joint",
"right 4th costosternal joint",
"bilateral 5th costosternal joints",
"left 5th costosternal joint",
"right 5th costosternal joint",
"bilateral 6th costosternal joints",
"left 6th costosternal joint",
"right 6th costosternal joint",
"bilateral 7th costosternal joints",
"left 7th costosternal joint",
"right 7th costosternal joint",
"bilateral shoulders",
"bilateral clavicles",
"bilateral distal clavicles",
"left distal clavicle",
"right distal clavicle",
"bilateral proximal clavicles",
"left proximal clavicle",
"right proximal clavicle",
"left clavicle",
"right clavicle",
"bilateral scapulae",
"left scapula",
"right scapula",
"bilateral acromioclavicular joints",
"left acromioclavicular joint",
"right acromioclavicular joint",
"left shoulder",
"right shoulder",
"bilateral humeri",
"bilateral proximal humeri",
"bilateral humeral heads",
"left humeral head",
"right humeral head",
"left proximal humerus",
"right proximal humerus",
"bilateral humeral shafts",
"left humeral shaft",
"right humeral shaft",
"bilateral distal humeri",
"left distal humerus",
"right distal humerus",
"left humerus",
"right humerus",
"bilateral elbows",
"left elbow",
"right elbow",
"bilateral radii/ulnae",
"bilateral proximal radii/ulnae",
"left proximal radius/ulna",
"right proximal radius/ulna",
"bilateral distal radii/ulnae",
"left distal radius/ulna",
"right distal radius/ulna",
"left radius/ulna",
"right radius/ulna",
"bilateral radii",
"bilateral proximal radii",
"left proximal radius",
"right proximal radius",
"bilateral distal radii",
"left distal radius",
"right distal radius",
"left radius",
"right radius",
"bilateral ulnae",
"bilateral proximal ulnae",
"left proximal ulna",
"right proximal ulna",
"bilateral distal ulnae",
"left distal ulna",
"right distal ulna",
"left ulna",
"right ulna",
"bilateral wrists",
"left wrist",
"right wrist",
"bilateral hands",
"left hand",
"right hand",
"bilateral pelvic bones",
"bilateral ilia",
"left ilium",
"right ilium",
"bilateral iliac crests",
"left iliac crest",
"right iliac crest",
"bilateral ischia",
"left ischium",
"right ischium",
"bilateral ischial tuberosities",
"left ischial tuberosity",
"right ischial tuberosity",
"bilateral pubes",
"bilateral superior pubic rami",
"left superior pubic ramus",
"right superior pubic ramus",
"bilateral inferior pubic rami",
"left inferior pubic ramus",
"right inferior pubic ramus",
"left pubis",
"right pubis",
"bilateral acetabula",
"left acetabulum",
"right acetabulum",
"left pelvic bones",
"right pelvic bones",
"bilateral hips",
"left hip",
"right hip",
"bilateral femora",
"bilateral proximal femora",
"bilateral femoral heads",
"left femoral head",
"right femoral head",
"bilateral femoral greater trochanters",
"left femoral greater trochanter",
"right femoral greater trochanter",
"bilateral femoral lesser trochanters",
"left femoral lesser trochanter",
"right femoral lesser trochanter",
"left proximal femur",
"right proximal femur",
"bilateral femoral shafts",
"left femoral shaft",
"right femoral shaft",
"bilateral distal femora",
"left distal femur",
"right distal femur",
"left femur",
"right femur",
"bilateral knees",
"left knee",
"right knee",
"bilateral tibiae/fibulae",
"bilateral proximal tibiae/fibulae",
"left proximal tibia/fibula",
"right proximal tibia/fibula",
"bilateral distal tibiae/fibulae",
"left distal tibia/fibula",
"right distal tibia/fibula",
"left tibia/fibula",
"right tibia/fibula",
"bilateral tibiae",
"bilateral proximal tibiae",
"left proximal tibia",
"right proximal tibia",
"bilateral distal tibiae",
"left distal tibia",
"right distal tibia",
"left tibia",
"right tibia",
"bilateral fibulae",
"bilateral proximal fibulae",
"left proximal fibula",
"right proximal fibula",
"bilateral distal fibulae",
"left distal fibula",
"right distal fibula",
"left fibula",
"right fibula",
"bilateral ankles",
"left ankle",
"right ankle",
"bilateral feet",
"bilateral calcanei",
"left calcaneus",
"right calcaneus",
"left foot",
"right foot",
];
